import type { ThemeSpec, TokenColorRule, SemanticTokenRule, ThemeDefinition } from "../types.ts";
import { alpha, contrastForeground, lineHighlight, lineHighlightBorder } from "../utils.ts";

export const buildTokenColors = (theme: ThemeSpec): TokenColorRule[] => {
  const base = theme.base30;
  const syntax = theme.base16;

  return [
    {
      name: "Comments",
      scope: ["comment", "punctuation.definition.comment"],
      settings: { foreground: base.greyFg }
    },
    {
      name: "Strings",
      scope: ["string", "string.quoted", "string.template", "string.interpolated", "meta.embedded.assembly"],
      settings: { foreground: syntax.base0B }
    },
    {
      name: "Regular Expressions",
      scope: ["string.regexp", "constant.other.character-class.regexp"],
      settings: { foreground: syntax.base0C }
    },
    {
      name: "Numbers And Booleans",
      scope: ["constant.numeric", "constant.language.boolean", "constant.language.null", "constant.character.escape"],
      settings: { foreground: syntax.base09 }
    },
    {
      name: "Constants",
      scope: ["constant", "constant.other", "support.constant"],
      settings: { foreground: syntax.base09 }
    },
    {
      name: "Variables",
      scope: ["variable", "meta.definition.variable", "support.variable"],
      settings: { foreground: syntax.base05 }
    },
    {
      name: "Builtin Variables And Parameters",
      scope: ["variable.language", "variable.parameter", "variable.other.readwrite.alias", "meta.parameter"],
      settings: { foreground: syntax.base08 }
    },
    {
      name: "Properties And Keys",
      scope: ["variable.other.property", "meta.object-literal.key", "support.type.property-name", "entity.other.attribute-name"],
      settings: { foreground: syntax.base08 }
    },
    {
      name: "Functions And Methods",
      scope: ["entity.name.function", "support.function", "meta.function-call", "variable.function", "meta.method-call", "entity.name.method"],
      settings: { foreground: syntax.base0D }
    },
    {
      name: "Keywords",
      scope: ["keyword", "keyword.control", "keyword.operator.expression", "storage", "storage.modifier", "keyword.other.unit"],
      settings: { foreground: syntax.base0E }
    },
    {
      name: "Types",
      scope: ["storage.type", "support.type", "entity.name.type", "entity.name.class", "entity.name.namespace", "entity.name.scope-resolution"],
      settings: { foreground: syntax.base0A }
    },
    {
      name: "Constructors And Specials",
      scope: ["meta.function-call.constructor", "support.class", "support.type.builtin", "constant.other.symbol"],
      settings: { foreground: syntax.base0C }
    },
    {
      name: "Tag Names",
      scope: ["entity.name.tag", "meta.tag.sgml", "meta.tag.structure.any.html"],
      settings: { foreground: syntax.base0A }
    },
    {
      name: "Tag Delimiters And Punctuation",
      scope: ["punctuation.definition.tag", "punctuation.separator.key-value", "punctuation.separator.delimiter", "punctuation.terminator", "meta.brace"],
      settings: { foreground: syntax.base0F }
    },
    {
      name: "Operators",
      scope: ["keyword.operator", "punctuation.accessor", "punctuation.definition.generic"],
      settings: { foreground: syntax.base05 }
    },
    {
      name: "Invalid",
      scope: ["invalid", "invalid.illegal"],
      settings: { foreground: syntax.base08 }
    },
    {
      name: "Markup Headings",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: syntax.base0D }
    },
    {
      name: "Markup Emphasis",
      scope: ["markup.bold", "markup.italic"],
      settings: { foreground: syntax.base09 }
    },
    {
      name: "Markup Links",
      scope: ["markup.underline.link", "string.other.link"],
      settings: { foreground: syntax.base0C, fontStyle: "underline" }
    },
    {
      name: "Diff Inserted",
      scope: ["markup.inserted", "meta.diff.header.from-file"],
      settings: { foreground: base.green }
    },
    {
      name: "Diff Removed",
      scope: ["markup.deleted", "meta.diff.header.to-file"],
      settings: { foreground: base.red }
    },
    {
      name: "Diff Changed",
      scope: ["markup.changed"],
      settings: { foreground: base.lightGrey }
    }
  ];
};

export const buildSemanticTokenColors = (theme: ThemeSpec): Record<string, SemanticTokenRule> => {
  const base = theme.base30;
  const syntax = theme.base16;

  return {
    comment: base.greyFg,
    string: syntax.base0B,
    regexp: syntax.base0F,
    number: syntax.base09,
    boolean: syntax.base09,
    keyword: syntax.base0E,
    operator: syntax.base05,
    namespace: syntax.base08,
    type: syntax.base0A,
    typeParameter: syntax.base0A,
    class: syntax.base0E,
    interface: syntax.base0E,
    enum: syntax.base0A,
    enumMember: syntax.base09,
    struct: syntax.base0E,
    function: syntax.base0D,
    method: syntax.base0D,
    decorator: syntax.base0D,
    macro: syntax.base08,
    variable: syntax.base05,
    parameter: syntax.base08,
    property: syntax.base08,
    label: syntax.base0A,
    event: syntax.base08,
    modifier: syntax.base08,
    "variable.defaultLibrary": syntax.base09,
    "variable.readonly.defaultLibrary": syntax.base09,
    "type.defaultLibrary": syntax.base0A
  };
};

export const buildVsCodeColors = (theme: ThemeSpec): Record<string, string> => {
  const base = theme.base30;
  const syntax = theme.base16;
  const onAccent = contrastForeground(theme, true);

  return {
    foreground: base.white,
    disabledForeground: base.lightGrey,
    errorForeground: base.red,
    focusBorder: base.blue,
    contrastBorder: base.line,
    contrastActiveBorder: base.blue,
    "selection.background": alpha(base.blue, 0.24),
    "textLink.foreground": base.teal,
    "textLink.activeForeground": syntax.base0D,
    "textPreformat.foreground": base.sun,
    "textBlockQuote.background": base.black2,
    "textBlockQuote.border": base.line,
    "textCodeBlock.background": base.black2,
    "textSeparator.foreground": base.line,
    descriptionForeground: base.lightGrey,
    "icon.foreground": base.blue,
    "sash.hoverBorder": base.blue,
    "badge.background": base.blue,
    "badge.foreground": onAccent,
    "progressBar.background": base.blue,
    "titleBar.activeBackground": base.black2,
    "titleBar.activeForeground": base.white,
    "titleBar.inactiveBackground": base.statuslineBg,
    "titleBar.inactiveForeground": base.lightGrey,
    "activityBar.background": base.darkerBlack,
    "activityBar.foreground": base.white,
    "activityBar.inactiveForeground": base.lightGrey,
    "activityBar.activeBorder": base.blue,
    "activityBarBadge.background": base.green,
    "activityBarBadge.foreground": onAccent,
    "sideBar.background": base.black,
    "sideBar.foreground": base.white,
    "sideBar.border": base.line,
    "sideBarTitle.foreground": base.white,
    "sideBarSectionHeader.background": base.black2,
    "sideBarSectionHeader.foreground": base.white,
    "sideBarSectionHeader.border": base.line,
    "list.activeSelectionBackground": alpha(base.blue, 0.16),
    "list.activeSelectionForeground": base.white,
    "list.inactiveSelectionBackground": alpha(base.oneBg3, 0.84),
    "list.inactiveSelectionForeground": base.white,
    "list.hoverBackground": alpha(base.oneBg2, 0.72),
    "list.hoverForeground": base.white,
    "list.focusBackground": alpha(base.blue, 0.2),
    "list.focusForeground": base.white,
    "list.highlightForeground": base.teal,
    "list.errorForeground": base.red,
    "list.warningForeground": base.yellow,
    "tree.indentGuidesStroke": base.line,
    "editorGroupHeader.tabsBackground": base.statuslineBg,
    "editorGroupHeader.tabsBorder": base.line,
    "tab.border": base.line,
    "tab.activeBackground": base.black,
    "tab.activeForeground": base.white,
    "tab.activeBorderTop": base.blue,
    "tab.inactiveBackground": base.black2,
    "tab.inactiveForeground": base.lightGrey,
    "tab.inactiveModifiedBorder": base.yellow,
    "tab.unfocusedActiveBorderTop": alpha(base.blue, 0.55),
    "tab.unfocusedInactiveForeground": base.greyFg2,
    "editor.background": base.black,
    "editor.foreground": base.white,
    "editorLineNumber.foreground": base.greyFg,
    "editorLineNumber.activeForeground": base.blue,
    "editorCursor.foreground": base.white,
    "editorCursor.background": base.black,
    "editor.selectionBackground": alpha(base.blue, 0.22),
    "editor.selectionHighlightBackground": alpha(base.teal, 0.14),
    "editor.inactiveSelectionBackground": alpha(base.oneBg3, 0.72),
    "editor.wordHighlightBackground": alpha(base.yellow, 0.14),
    "editor.wordHighlightStrongBackground": alpha(base.orange, 0.18),
    "editor.findMatchBackground": alpha(base.green, 0.32),
    "editor.findMatchBorder": base.green,
    "editor.findMatchHighlightBackground": alpha(base.teal, 0.14),
    "editor.findRangeHighlightBackground": alpha(base.oneBg3, 0.55),
    "editor.hoverHighlightBackground": alpha(base.oneBg2, 0.45),
    "editor.lineHighlightBackground": lineHighlight(theme),
    "editor.lineHighlightBorder": lineHighlightBorder(theme),
    "editorLink.activeForeground": base.teal,
    "editorWhitespace.foreground": alpha(base.grey, 0.65),
    "editorIndentGuide.background1": base.line,
    "editorIndentGuide.activeBackground1": base.lightGrey,
    "editorRuler.foreground": base.line,
    "editorBracketMatch.background": alpha(base.oneBg3, 0.85),
    "editorBracketMatch.border": base.teal,
    "editorBracketHighlight.foreground1": base.blue,
    "editorBracketHighlight.foreground2": base.green,
    "editorBracketHighlight.foreground3": base.yellow,
    "editorBracketHighlight.foreground4": base.purple,
    "editorBracketHighlight.foreground5": base.orange,
    "editorBracketHighlight.foreground6": base.teal,
    "editorBracketPairGuide.background1": alpha(base.blue, 0.26),
    "editorBracketPairGuide.background2": alpha(base.green, 0.26),
    "editorBracketPairGuide.background3": alpha(base.yellow, 0.26),
    "editorBracketPairGuide.background4": alpha(base.purple, 0.26),
    "editorBracketPairGuide.background5": alpha(base.orange, 0.26),
    "editorBracketPairGuide.background6": alpha(base.teal, 0.26),
    "editorBracketPairGuide.activeBackground1": base.blue,
    "editorBracketPairGuide.activeBackground2": base.green,
    "editorBracketPairGuide.activeBackground3": base.yellow,
    "editorBracketPairGuide.activeBackground4": base.purple,
    "editorBracketPairGuide.activeBackground5": base.orange,
    "editorBracketPairGuide.activeBackground6": base.teal,
    "editorGutter.background": base.black,
    "editorGutter.modifiedBackground": base.blue,
    "editorGutter.addedBackground": base.green,
    "editorGutter.deletedBackground": base.red,
    "editorError.foreground": base.red,
    "editorWarning.foreground": base.yellow,
    "editorInfo.foreground": base.green,
    "editorHint.foreground": base.purple,
    "editorOverviewRuler.errorForeground": alpha(base.red, 0.8),
    "editorOverviewRuler.warningForeground": alpha(base.yellow, 0.8),
    "editorOverviewRuler.infoForeground": alpha(base.green, 0.8),
    "editorOverviewRuler.bracketMatchForeground": alpha(base.teal, 0.8),
    "editorOverviewRuler.modifiedForeground": alpha(base.blue, 0.8),
    "editorOverviewRuler.addedForeground": alpha(base.green, 0.8),
    "editorOverviewRuler.deletedForeground": alpha(base.red, 0.8),
    "editorWidget.background": base.black2,
    "editorWidget.foreground": base.white,
    "editorWidget.border": base.line,
    "editorSuggestWidget.background": base.black2,
    "editorSuggestWidget.border": base.line,
    "editorSuggestWidget.foreground": base.white,
    "editorSuggestWidget.highlightForeground": base.teal,
    "editorSuggestWidget.selectedBackground": alpha(base.oneBg3, 0.92),
    "editorHoverWidget.background": base.black2,
    "editorHoverWidget.foreground": base.white,
    "editorHoverWidget.border": base.line,
    "editorMarkerNavigation.background": base.black2,
    "peekView.border": base.line,
    "peekViewEditor.background": base.black,
    "peekViewEditor.matchHighlightBackground": alpha(base.green, 0.22),
    "peekViewResult.background": base.black2,
    "peekViewResult.selectionBackground": alpha(base.blue, 0.18),
    "peekViewResult.matchHighlightBackground": alpha(base.teal, 0.16),
    "peekViewTitle.background": base.statuslineBg,
    "peekViewTitleLabel.foreground": base.white,
    "peekViewTitleDescription.foreground": base.lightGrey,
    "panel.background": base.black2,
    "panel.border": base.line,
    "panelTitle.activeBorder": base.blue,
    "panelTitle.activeForeground": base.white,
    "panelTitle.inactiveForeground": base.lightGrey,
    "statusBar.background": base.statuslineBg,
    "statusBar.foreground": base.white,
    "statusBar.border": base.line,
    "statusBar.debuggingBackground": base.orange,
    "statusBar.debuggingForeground": onAccent,
    "statusBar.noFolderBackground": base.black2,
    "statusBarItem.hoverBackground": alpha(base.oneBg3, 0.9),
    "statusBarItem.prominentBackground": alpha(base.oneBg2, 0.9),
    "statusBarItem.remoteBackground": base.blue,
    "statusBarItem.remoteForeground": onAccent,
    "terminal.background": base.black,
    "terminal.foreground": base.white,
    "terminal.selectionBackground": alpha(base.blue, 0.24),
    "terminal.border": base.line,
    "terminalCursor.foreground": base.white,
    "terminalCursor.background": base.black,
    "terminal.ansiBlack": base.black2,
    "terminal.ansiRed": base.red,
    "terminal.ansiGreen": base.green,
    "terminal.ansiYellow": base.yellow,
    "terminal.ansiBlue": base.blue,
    "terminal.ansiMagenta": base.purple,
    "terminal.ansiCyan": base.cyan,
    "terminal.ansiWhite": base.white,
    "terminal.ansiBrightBlack": base.greyFg,
    "terminal.ansiBrightRed": base.babyPink,
    "terminal.ansiBrightGreen": base.vibrantGreen,
    "terminal.ansiBrightYellow": base.sun,
    "terminal.ansiBrightBlue": syntax.base0D,
    "terminal.ansiBrightMagenta": base.darkPurple,
    "terminal.ansiBrightCyan": base.teal,
    "terminal.ansiBrightWhite": syntax.base07,
    "input.background": base.black2,
    "input.foreground": base.white,
    "input.border": base.line,
    "input.placeholderForeground": base.lightGrey,
    "inputOption.activeBorder": base.blue,
    "inputValidation.errorBackground": alpha(base.red, 0.1),
    "inputValidation.errorBorder": base.red,
    "inputValidation.warningBackground": alpha(base.yellow, 0.1),
    "inputValidation.warningBorder": base.yellow,
    "inputValidation.infoBackground": alpha(base.blue, 0.1),
    "inputValidation.infoBorder": base.blue,
    "dropdown.background": base.black2,
    "dropdown.foreground": base.white,
    "dropdown.border": base.line,
    "checkbox.background": base.black2,
    "checkbox.border": base.line,
    "checkbox.foreground": base.white,
    "button.background": base.blue,
    "button.foreground": onAccent,
    "button.hoverBackground": syntax.base0D,
    "button.secondaryBackground": base.oneBg2,
    "button.secondaryForeground": base.white,
    "button.secondaryHoverBackground": base.oneBg3,
    "quickInput.background": base.black2,
    "quickInput.foreground": base.white,
    "quickInputList.focusBackground": alpha(base.oneBg3, 0.92),
    "pickerGroup.border": base.line,
    "pickerGroup.foreground": base.teal,
    "menu.background": base.black2,
    "menu.foreground": base.white,
    "menu.selectionBackground": alpha(base.oneBg3, 0.92),
    "menu.selectionForeground": base.white,
    "menu.border": base.line,
    "notificationCenterHeader.background": base.statuslineBg,
    "notificationCenterHeader.foreground": base.white,
    "notifications.background": base.black2,
    "notifications.foreground": base.white,
    "notifications.border": base.line,
    "scrollbar.shadow": alpha(base.black, 0.45),
    "scrollbarSlider.background": alpha(base.oneBg3, 0.65),
    "scrollbarSlider.hoverBackground": alpha(base.grey, 0.7),
    "scrollbarSlider.activeBackground": alpha(base.greyFg2, 0.82),
    "breadcrumb.background": base.black,
    "breadcrumb.foreground": base.lightGrey,
    "breadcrumb.activeSelectionForeground": base.white,
    "breadcrumb.focusForeground": base.teal,
    "commandCenter.background": alpha(base.oneBg2, 0.7),
    "commandCenter.foreground": base.white,
    "commandCenter.border": base.line,
    "minimap.background": base.black,
    "minimap.selectionHighlight": alpha(base.blue, 0.18),
    "minimap.findMatchHighlight": alpha(base.green, 0.3),
    "minimap.errorHighlight": alpha(base.red, 0.45),
    "minimap.warningHighlight": alpha(base.yellow, 0.45),
    "minimapGutter.addedBackground": base.green,
    "minimapGutter.modifiedBackground": base.blue,
    "minimapGutter.deletedBackground": base.red,
    "gitDecoration.addedResourceForeground": base.green,
    "gitDecoration.modifiedResourceForeground": base.blue,
    "gitDecoration.deletedResourceForeground": base.red,
    "gitDecoration.renamedResourceForeground": base.teal,
    "gitDecoration.untrackedResourceForeground": base.green,
    "gitDecoration.ignoredResourceForeground": base.lightGrey,
    "diffEditor.insertedTextBackground": alpha(base.green, 0.16),
    "diffEditor.removedTextBackground": alpha(base.red, 0.14),
    "diffEditor.insertedLineBackground": alpha(base.green, 0.08),
    "diffEditor.removedLineBackground": alpha(base.red, 0.08),
    "diffEditor.diagonalFill": base.line,
    "diffEditor.border": base.line,
    "diffEditorOverview.insertedForeground": alpha(base.green, 0.8),
    "diffEditorOverview.removedForeground": alpha(base.red, 0.8),
    "merge.currentHeaderBackground": alpha(base.blue, 0.2),
    "merge.currentContentBackground": alpha(base.blue, 0.08),
    "merge.incomingHeaderBackground": alpha(base.green, 0.2),
    "merge.incomingContentBackground": alpha(base.green, 0.08),
    "merge.border": base.line,
    "merge.commonContentBackground": alpha(base.oneBg3, 0.35),
    "merge.commonHeaderBackground": alpha(base.grey, 0.35),
    "problemsErrorIcon.foreground": base.red,
    "problemsWarningIcon.foreground": base.yellow,
    "problemsInfoIcon.foreground": base.green,
    "debugIcon.breakpointForeground": base.red,
    "debugIcon.breakpointDisabledForeground": base.lightGrey,
    "debugIcon.startForeground": base.green,
    "debugIcon.pauseForeground": base.yellow,
    "debugIcon.stopForeground": base.red,
    "debugTokenExpression.string": syntax.base0B,
    "debugTokenExpression.number": syntax.base09,
    "debugTokenExpression.boolean": syntax.base09,
    "debugTokenExpression.name": syntax.base0D,
    "settings.headerForeground": base.white,
    "settings.modifiedItemIndicator": base.green,
    "settings.dropdownBackground": base.black2,
    "settings.dropdownForeground": base.white,
    "settings.dropdownBorder": base.line,
    "settings.numberInputBackground": base.black2,
    "settings.numberInputForeground": base.white,
    "settings.numberInputBorder": base.line,
    "settings.textInputBackground": base.black2,
    "settings.textInputForeground": base.white,
    "settings.textInputBorder": base.line,
    "chat.background": base.oneBg,
    "chat.foreground": base.white,
    "chat.border": base.line,
    "chat.slashCommandBackground": alpha(base.oneBg2, 0.9),
    "chat.slashCommandForeground": base.teal,
    "chat.requestBackground": base.black2,
    "chat.requestBorder": base.line,
    "chat.responseBackground": base.oneBg,
    "inlineChat.background": base.black2,
    "inlineChat.border": base.line,
    "inlineChat.foreground": base.white,
    "inlineChatInput.border": base.line,
    "inlineChatInput.focusBorder": base.blue,
    "symbolIcon.classForeground": syntax.base0A,
    "symbolIcon.functionForeground": syntax.base0D,
    "symbolIcon.variableForeground": syntax.base05,
    "symbolIcon.methodForeground": syntax.base0D,
    "symbolIcon.propertyForeground": syntax.base08,
    "symbolIcon.interfaceForeground": syntax.base0E,
    "symbolIcon.enumForeground": syntax.base0A,
    "symbolIcon.constantForeground": syntax.base09,
    "symbolIcon.namespaceForeground": syntax.base08,
    "symbolIcon.moduleForeground": syntax.base0E,
    "symbolIcon.structForeground": syntax.base0E,
    "profileBadge.background": base.blue,
    "profileBadge.foreground": onAccent,
    "welcomePage.tileBackground": base.oneBg,
    "welcomePage.tileHoverBackground": base.oneBg2,
    "welcomePage.progress.background": base.oneBg3,
    "welcomePage.progress.foreground": base.blue,
    "ports.iconRunningProcessForeground": base.green
  };
};

export const buildTheme = (theme: ThemeSpec): ThemeDefinition => ({
  $schema: "vscode://schemas/color-theme",
  name: theme.displayName,
  type: theme.type,
  semanticHighlighting: true,
  colors: buildVsCodeColors(theme),
  tokenColors: buildTokenColors(theme),
  semanticTokenColors: buildSemanticTokenColors(theme)
});
