import type { ThemeSpec, ThemeDefinition } from "../types.ts";
import type { ResolvedThemeModel } from "../derive/types.ts";
import { deriveThemeModel } from "../derive/theme-model.ts";
import { alpha, contrastForeground, lineHighlight, lineHighlightBorder } from "../utils.ts";
import { toVsCodeTokenColors, toSemanticTokens } from "../syntax/index.ts";

const baseSemanticTokens = (theme: ThemeSpec) => {
  const syntax = theme.base16;
  return {
    typeParameter: syntax.base0A,
    class: syntax.base0E,
    interface: syntax.base0E,
    enum: syntax.base0A,
    enumMember: syntax.base09,
    struct: syntax.base0E,
    decorator: syntax.base0D,
    macro: syntax.base08,
    label: syntax.base0A,
    event: syntax.base08,
    modifier: syntax.base08,
    operator: syntax.base05,
    "variable.defaultLibrary": syntax.base09,
    "variable.readonly.defaultLibrary": syntax.base09,
    "type.defaultLibrary": syntax.base0A,
    "variable.readonly": syntax.base05,
    selfKeyword: syntax.base0E
  };
};

export const buildTokenColorsFromModel = (model: ResolvedThemeModel) =>
  toVsCodeTokenColors(model.syntax);

export const buildSemanticTokenColorsFromModel = (model: ResolvedThemeModel) => ({
  ...toSemanticTokens(model.syntax),
  ...baseSemanticTokens(model.theme)
});

export const buildTokenColors = (theme: ThemeSpec) => buildTokenColorsFromModel(deriveThemeModel(theme));

export const buildSemanticTokenColors = (theme: ThemeSpec) =>
  buildSemanticTokenColorsFromModel(deriveThemeModel(theme));

export const buildVsCodeColorsFromModel = (model: ResolvedThemeModel): Record<string, string> => {
  const theme = model.theme;
  const base = theme.base30;
  const syntax = theme.base16;
  const ladder = model.surfaces.vscode;
  const hints = model.integrations;
  const extra = model.vscodeExtras;
  const sep = model.ui;
  const term = hints.terminal;
  const git = hints.git;
  const diag = hints.diagnostics;
  const onAccent = contrastForeground(theme, true);

  return {
    foreground: base.white,
    disabledForeground: base.lightGrey,
    errorForeground: base.red,
    focusBorder: base.blue,
    contrastBorder: sep.borderStrong,
    contrastActiveBorder: base.blue,
    "selection.background": alpha(base.blue, 0.24),
    "textLink.foreground": base.teal,
    "textLink.activeForeground": syntax.base0D,
    "textPreformat.foreground": base.sun,
    "textBlockQuote.background": ladder.overlay,
    "textBlockQuote.border": sep.borderSubtle,
    "textCodeBlock.background": ladder.overlay,
    "textSeparator.foreground": sep.borderSubtle,
    descriptionForeground: base.lightGrey,
    "icon.foreground": base.blue,
    "sash.hoverBorder": base.blue,
    "badge.background": base.blue,
    "badge.foreground": onAccent,
    "progressBar.background": base.blue,
    "titleBar.activeBackground": ladder.overlay,
    "titleBar.activeForeground": base.white,
    "titleBar.inactiveBackground": ladder.chrome,
    "titleBar.inactiveForeground": base.lightGrey,
    "activityBar.background": ladder.sidebar,
    "activityBar.foreground": base.white,
    "activityBar.inactiveForeground": base.lightGrey,
    "activityBar.activeBorder": base.blue,
    "activityBarBadge.background": base.green,
    "activityBarBadge.foreground": onAccent,
    "sideBar.background": ladder.sidebar,
    "sideBar.foreground": base.white,
    "sideBar.border": sep.borderStrong,
    "sideBarTitle.foreground": base.white,
    "sideBarSectionHeader.background": ladder.overlay,
    "sideBarSectionHeader.foreground": base.white,
    "sideBarSectionHeader.border": sep.borderSubtle,
    "list.activeSelectionBackground": alpha(base.blue, 0.35),
    "list.activeSelectionForeground": base.white,
    "list.inactiveSelectionBackground": alpha(base.oneBg3, 0.84),
    "list.inactiveSelectionForeground": base.white,
    "list.hoverBackground": alpha(base.oneBg2, 0.72),
    "list.hoverForeground": base.white,
    "list.focusBackground": alpha(base.blue, 0.4),
    "list.focusForeground": base.white,
    "list.highlightForeground": base.teal,
    "list.errorForeground": base.red,
    "list.warningForeground": base.yellow,
    "tree.indentGuidesStroke": sep.treeIndent,
    "editorGroupHeader.tabsBackground": ladder.chrome,
    "editorGroupHeader.tabsBorder": sep.borderStrong,
    "tab.border": sep.borderStrong,
    "tab.activeBackground": hints.tabActiveBg,
    "tab.activeForeground": base.white,
    "tab.activeBorderTop": base.blue,
    "tab.inactiveBackground": hints.tabInactiveBg,
    "tab.inactiveForeground": base.lightGrey,
    "tab.inactiveModifiedBorder": hints.tabModifiedBorder,
    "tab.unfocusedActiveBorderTop": alpha(base.blue, 0.55),
    "tab.unfocusedInactiveForeground": base.greyFg2,
    "editor.background": ladder.editor,
    "editor.foreground": base.white,
    "editorLineNumber.foreground": hints.lineNumberColor,
    "editorLineNumber.activeForeground": base.blue,
    "editorCursor.foreground": base.white,
    "editorCursor.background": ladder.editor,
    "editor.selectionBackground": alpha(base.blue, 0.35),
    "editor.selectionHighlightBackground": alpha(base.teal, 0.14),
    "editor.inactiveSelectionBackground": alpha(base.oneBg3, 0.72),
    "editor.wordHighlightBackground": alpha(base.yellow, 0.14),
    "editor.wordHighlightStrongBackground": alpha(base.orange, 0.18),
    "editor.findMatchBackground": alpha(base.green, 0.32),
    "editor.findMatchBorder": base.green,
    "editor.findMatchHighlightBackground": alpha(base.teal, 0.14),
    "editor.findRangeHighlightBackground": alpha(base.oneBg3, 0.55),
    "editor.hoverHighlightBackground": alpha(base.oneBg2, 0.45),
    "editor.lineHighlightBackground": hints.cursorLineBg,
    "editor.lineHighlightBorder": lineHighlightBorder(theme),
    "editorLink.activeForeground": base.teal,
    "editorWhitespace.foreground": alpha(base.grey, 0.65),
    "editorIndentGuide.background1": sep.indentGuide,
    "editorIndentGuide.activeBackground1": sep.indentGuideActive,
    "editorRuler.foreground": sep.wrapGuide,
    "editorBracketMatch.background": alpha(base.oneBg3, 0.85),
    "editorBracketMatch.border": base.teal,
    "editorBracketHighlight.foreground1": base.blue,
    "editorBracketHighlight.foreground2": base.green,
    "editorBracketHighlight.foreground3": base.yellow,
    "editorBracketHighlight.foreground4": base.purple,
    "editorBracketHighlight.foreground5": base.orange,
    "editorBracketHighlight.foreground6": base.teal,
    "editorBracketPairGuide.background1": alpha(base.blue, 0.26),
    "editorBracketPairGuide.background2": alpha(base.green, 0.26),
    "editorBracketPairGuide.background3": alpha(base.yellow, 0.26),
    "editorBracketPairGuide.background4": alpha(base.purple, 0.26),
    "editorBracketPairGuide.background5": alpha(base.orange, 0.26),
    "editorBracketPairGuide.background6": alpha(base.teal, 0.26),
    "editorBracketPairGuide.activeBackground1": base.blue,
    "editorBracketPairGuide.activeBackground2": base.green,
    "editorBracketPairGuide.activeBackground3": base.yellow,
    "editorBracketPairGuide.activeBackground4": base.purple,
    "editorBracketPairGuide.activeBackground5": base.orange,
    "editorBracketPairGuide.activeBackground6": base.teal,
    "editorGutter.background": ladder.editor,
    "editorGutter.modifiedBackground": base.blue,
    "editorGutter.addedBackground": base.green,
    "editorGutter.deletedBackground": base.red,
    "editorError.foreground": diag.error,
    "editorWarning.foreground": diag.warning,
    "editorInfo.foreground": diag.info,
    "editorHint.foreground": diag.hint,
    "editorOverviewRuler.errorForeground": alpha(base.red, 0.8),
    "editorOverviewRuler.warningForeground": alpha(base.yellow, 0.8),
    "editorOverviewRuler.infoForeground": alpha(base.green, 0.8),
    "editorOverviewRuler.bracketMatchForeground": alpha(base.teal, 0.8),
    "editorOverviewRuler.modifiedForeground": alpha(base.blue, 0.8),
    "editorOverviewRuler.addedForeground": alpha(base.green, 0.8),
    "editorOverviewRuler.deletedForeground": alpha(base.red, 0.8),
    "editorWidget.background": ladder.overlay,
    "editorWidget.foreground": base.white,
    "editorWidget.border": sep.border,
    "editorSuggestWidget.background": ladder.overlay,
    "editorSuggestWidget.border": sep.border,
    "editorSuggestWidget.foreground": base.white,
    "editorSuggestWidget.highlightForeground": base.teal,
    "editorSuggestWidget.selectedBackground": alpha(hints.pmenuSelBg, 0.35),
    "editorHoverWidget.background": ladder.overlay,
    "editorHoverWidget.foreground": base.white,
    "editorHoverWidget.border": sep.border,
    "editorMarkerNavigation.background": ladder.overlay,
    "peekView.border": sep.border,
    "peekViewEditor.background": ladder.editor,
    "peekViewEditor.matchHighlightBackground": alpha(base.green, 0.22),
    "peekViewResult.background": ladder.overlay,
    "peekViewResult.selectionBackground": alpha(base.blue, 0.35),
    "peekViewResult.matchHighlightBackground": alpha(base.teal, 0.16),
    "peekViewTitle.background": ladder.chrome,
    "peekViewTitleLabel.foreground": base.white,
    "peekViewTitleDescription.foreground": base.lightGrey,
    "panel.background": ladder.overlay,
    "panel.border": sep.borderStrong,
    "panelTitle.activeBorder": base.blue,
    "panelTitle.activeForeground": base.white,
    "panelTitle.inactiveForeground": base.lightGrey,
    "statusBar.background": ladder.chrome,
    "statusBar.foreground": base.white,
    "statusBar.border": sep.borderStrong,
    "statusBar.debuggingBackground": base.orange,
    "statusBar.debuggingForeground": onAccent,
    "statusBar.noFolderBackground": ladder.overlay,
    "statusBarItem.hoverBackground": alpha(base.oneBg3, 0.9),
    "statusBarItem.prominentBackground": alpha(base.oneBg2, 0.9),
    "statusBarItem.remoteBackground": base.blue,
    "statusBarItem.remoteForeground": onAccent,
    "terminal.background": ladder.editor,
    "terminal.foreground": base.white,
    "terminal.selectionBackground": alpha(base.blue, 0.35),
    "terminal.border": sep.border,
    "terminalCursor.foreground": base.white,
    "terminalCursor.background": ladder.editor,
    "terminal.ansiBlack": term.black,
    "terminal.ansiRed": term.red,
    "terminal.ansiGreen": term.green,
    "terminal.ansiYellow": term.yellow,
    "terminal.ansiBlue": term.blue,
    "terminal.ansiMagenta": term.magenta,
    "terminal.ansiCyan": term.cyan,
    "terminal.ansiWhite": term.white,
    "terminal.ansiBrightBlack": term.brightBlack,
    "terminal.ansiBrightRed": term.brightRed,
    "terminal.ansiBrightGreen": term.brightGreen,
    "terminal.ansiBrightYellow": term.brightYellow,
    "terminal.ansiBrightBlue": term.brightBlue,
    "terminal.ansiBrightMagenta": term.brightMagenta,
    "terminal.ansiBrightCyan": term.brightCyan,
    "terminal.ansiBrightWhite": term.brightWhite,
    "input.background": ladder.overlay,
    "input.foreground": base.white,
    "input.border": sep.border,
    "input.placeholderForeground": base.lightGrey,
    "inputOption.activeBorder": base.blue,
    "inputValidation.errorBackground": alpha(base.red, 0.1),
    "inputValidation.errorBorder": base.red,
    "inputValidation.warningBackground": alpha(base.yellow, 0.1),
    "inputValidation.warningBorder": base.yellow,
    "inputValidation.infoBackground": alpha(base.blue, 0.1),
    "inputValidation.infoBorder": base.blue,
    "dropdown.background": ladder.overlay,
    "dropdown.foreground": base.white,
    "dropdown.border": sep.border,
    "checkbox.background": ladder.overlay,
    "checkbox.border": sep.border,
    "checkbox.foreground": base.white,
    "button.background": base.blue,
    "button.foreground": onAccent,
    "button.hoverBackground": syntax.base0D,
    "button.secondaryBackground": base.oneBg2,
    "button.secondaryForeground": base.white,
    "button.secondaryHoverBackground": base.oneBg3,
    "quickInput.background": ladder.overlay,
    "quickInput.foreground": base.white,
    "quickInputList.focusBackground": alpha(hints.pmenuSelBg, 0.35),
    "pickerGroup.border": sep.border,
    "pickerGroup.foreground": base.teal,
    "menu.background": ladder.overlay,
    "menu.foreground": base.white,
    "menu.selectionBackground": alpha(hints.pmenuSelBg, 0.35),
    "menu.selectionForeground": base.white,
    "menu.border": sep.border,
    "notificationCenterHeader.background": ladder.chrome,
    "notificationCenterHeader.foreground": base.white,
    "notifications.background": ladder.overlay,
    "notifications.foreground": base.white,
    "notifications.border": sep.border,
    "scrollbar.shadow": alpha(base.black, 0.45),
    "scrollbarSlider.background": alpha(base.oneBg3, 0.65),
    "scrollbarSlider.hoverBackground": alpha(base.grey, 0.7),
    "scrollbarSlider.activeBackground": alpha(base.greyFg2, 0.82),
    "breadcrumb.background": ladder.editor,
    "breadcrumb.foreground": base.lightGrey,
    "breadcrumb.activeSelectionForeground": base.white,
    "breadcrumb.focusForeground": base.teal,
    "commandCenter.background": alpha(base.oneBg2, 0.7),
    "commandCenter.foreground": base.white,
    "commandCenter.border": sep.border,
    "minimap.background": ladder.editor,
    "minimap.selectionHighlight": alpha(base.blue, 0.35),
    "minimap.findMatchHighlight": alpha(base.green, 0.3),
    "minimap.errorHighlight": alpha(base.red, 0.45),
    "minimap.warningHighlight": alpha(base.yellow, 0.45),
    "minimapGutter.addedBackground": base.green,
    "minimapGutter.modifiedBackground": base.blue,
    "minimapGutter.deletedBackground": base.red,
    "gitDecoration.addedResourceForeground": git.added,
    "gitDecoration.modifiedResourceForeground": git.modified,
    "gitDecoration.deletedResourceForeground": git.deleted,
    "gitDecoration.renamedResourceForeground": git.renamed,
    "gitDecoration.untrackedResourceForeground": git.added,
    "gitDecoration.ignoredResourceForeground": git.ignored,
    "diffEditor.insertedTextBackground": hints.diffAddedBg,
    "diffEditor.removedTextBackground": hints.diffRemovedBg,
    "diffEditor.insertedLineBackground": alpha(base.green, 0.08),
    "diffEditor.removedLineBackground": alpha(base.red, 0.08),
    "diffEditor.diagonalFill": sep.border,
    "diffEditor.border": sep.borderStrong,
    "diffEditorOverview.insertedForeground": alpha(base.green, 0.8),
    "diffEditorOverview.removedForeground": alpha(base.red, 0.8),
    "merge.currentHeaderBackground": alpha(base.blue, 0.2),
    "merge.currentContentBackground": alpha(base.blue, 0.08),
    "merge.incomingHeaderBackground": alpha(base.green, 0.2),
    "merge.incomingContentBackground": alpha(base.green, 0.08),
    "merge.border": sep.border,
    "merge.commonContentBackground": alpha(base.oneBg3, 0.35),
    "merge.commonHeaderBackground": alpha(base.grey, 0.35),
    "problemsErrorIcon.foreground": diag.error,
    "problemsWarningIcon.foreground": diag.warning,
    "problemsInfoIcon.foreground": diag.info,
    "debugIcon.breakpointForeground": base.red,
    "debugIcon.breakpointDisabledForeground": base.lightGrey,
    "debugIcon.startForeground": base.green,
    "debugIcon.pauseForeground": base.yellow,
    "debugIcon.stopForeground": base.red,
    "debugTokenExpression.string": syntax.base0B,
    "debugTokenExpression.number": syntax.base09,
    "debugTokenExpression.boolean": syntax.base09,
    "debugTokenExpression.name": syntax.base0D,
    "settings.headerForeground": base.white,
    "settings.modifiedItemIndicator": base.green,
    "settings.dropdownBackground": ladder.overlay,
    "settings.dropdownForeground": base.white,
    "settings.dropdownBorder": sep.border,
    "settings.numberInputBackground": ladder.overlay,
    "settings.numberInputForeground": base.white,
    "settings.numberInputBorder": sep.border,
    "settings.textInputBackground": ladder.overlay,
    "settings.textInputForeground": base.white,
    "settings.textInputBorder": sep.border,
    "chat.background": ladder.raised,
    "chat.foreground": base.white,
    "chat.border": sep.border,
    "chat.slashCommandBackground": alpha(base.oneBg2, 0.9),
    "chat.slashCommandForeground": base.teal,
    "chat.requestBackground": ladder.overlay,
    "chat.requestBorder": sep.border,
    "chat.responseBackground": ladder.raised,
    "inlineChat.background": ladder.overlay,
    "inlineChat.border": sep.border,
    "inlineChat.foreground": base.white,
    "inlineChatInput.border": sep.border,
    "inlineChatInput.focusBorder": base.blue,
    "profileBadge.background": base.blue,
    "profileBadge.foreground": onAccent,
    "welcomePage.tileBackground": ladder.raised,
    "welcomePage.tileHoverBackground": ladder.raisedHover,
    "welcomePage.progress.background": base.oneBg3,
    "welcomePage.progress.foreground": base.blue,
    "ports.iconRunningProcessForeground": base.green,
    ...extra
  };
};

export const buildVsCodeColors = (theme: ThemeSpec): Record<string, string> =>
  buildVsCodeColorsFromModel(deriveThemeModel(theme));

export const buildThemeFromModel = (model: ResolvedThemeModel): ThemeDefinition => ({
  $schema: "vscode://schemas/color-theme",
  name: model.theme.displayName,
  type: model.theme.type,
  semanticHighlighting: true,
  colors: buildVsCodeColorsFromModel(model),
  tokenColors: buildTokenColorsFromModel(model),
  semanticTokenColors: buildSemanticTokenColorsFromModel(model)
});

export const buildTheme = (theme: ThemeSpec): ThemeDefinition => buildThemeFromModel(deriveThemeModel(theme));
