import type { ThemeSpec, ZedSyntaxRule, ZedThemeDefinition } from "../types.ts";
import { alpha, lineHighlight } from "../utils.ts";

export const buildZedSyntax = (theme: ThemeSpec): Record<string, ZedSyntaxRule> => {
  const base = theme.base30;
  const syntax = theme.base16;
  const mutedHint = base.lightGrey;

  return {
    attribute: { color: syntax.base0A, font_style: null, font_weight: null },
    boolean: { color: syntax.base09, font_style: null, font_weight: null },
    character: { color: syntax.base0C, font_style: null, font_weight: null },
    "character.special": { color: syntax.base0F, font_style: null, font_weight: null },
    comment: { color: base.greyFg, font_style: null, font_weight: null },
    "comment.doc": { color: base.greyFg2, font_style: null, font_weight: null },
    constant: { color: syntax.base09, font_style: null, font_weight: null },
    "constant.builtin": { color: syntax.base09, font_style: null, font_weight: null },
    constructor: { color: syntax.base0C, font_style: null, font_weight: null },
    embedded: { color: syntax.base05, font_style: null, font_weight: null },
    emphasis: { color: syntax.base09, font_style: "italic", font_weight: null },
    function: { color: syntax.base0D, font_style: null, font_weight: null },
    "function.builtin": { color: syntax.base0D, font_style: null, font_weight: null },
    "function.call": { color: syntax.base0D, font_style: null, font_weight: null },
    "function.macro": { color: syntax.base08, font_style: null, font_weight: null },
    "function.method": { color: syntax.base0D, font_style: null, font_weight: null },
    "function.method.call": { color: syntax.base0D, font_style: null, font_weight: null },
    hint: { color: mutedHint, font_style: "italic", font_weight: null },
    keyword: { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.conditional": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.control": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.directive": { color: syntax.base0A, font_style: null, font_weight: null },
    "keyword.exception": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.function": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.import": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.operator": { color: syntax.base0E, font_style: null, font_weight: null },
    "keyword.repeat": { color: syntax.base0A, font_style: null, font_weight: null },
    "keyword.return": { color: syntax.base0E, font_style: null, font_weight: null },
    label: { color: syntax.base0A, font_style: null, font_weight: null },
    link_text: { color: base.teal, font_style: null, font_weight: null },
    link_uri: { color: base.teal, font_style: "italic", font_weight: null },
    module: { color: syntax.base08, font_style: null, font_weight: null },
    number: { color: syntax.base09, font_style: null, font_weight: null },
    "number.float": { color: syntax.base09, font_style: null, font_weight: null },
    operator: { color: syntax.base05, font_style: null, font_weight: null },
    property: { color: syntax.base08, font_style: null, font_weight: null },
    "property.json": { color: syntax.base08, font_style: null, font_weight: null },
    punctuation: { color: syntax.base0F, font_style: null, font_weight: null },
    "punctuation.bracket": { color: syntax.base0F, font_style: null, font_weight: null },
    "punctuation.delimiter": { color: syntax.base0F, font_style: null, font_weight: null },
    "punctuation.list_marker": { color: syntax.base08, font_style: null, font_weight: null },
    string: { color: syntax.base0B, font_style: null, font_weight: null },
    "string.documentation": { color: base.teal, font_style: null, font_weight: null },
    "string.escape": { color: syntax.base0C, font_style: null, font_weight: null },
    "string.regexp": { color: syntax.base0C, font_style: null, font_weight: null },
    "string.special": { color: syntax.base0F, font_style: null, font_weight: null },
    "string.special.symbol": { color: syntax.base09, font_style: null, font_weight: null },
    "string.special.url": { color: base.teal, font_style: "italic", font_weight: null },
    tag: { color: syntax.base0A, font_style: null, font_weight: null },
    "tag.attribute": { color: syntax.base08, font_style: null, font_weight: null },
    "tag.doctype": { color: syntax.base0E, font_style: null, font_weight: null },
    "tag.delimiter": { color: syntax.base0F, font_style: null, font_weight: null },
    "text.literal": { color: syntax.base05, font_style: null, font_weight: null },
    title: { color: syntax.base0D, font_style: null, font_weight: 700 },
    type: { color: syntax.base0A, font_style: null, font_weight: null },
    "type.builtin": { color: syntax.base0A, font_style: null, font_weight: null },
    "type.definition": { color: syntax.base0A, font_style: null, font_weight: null },
    "type.interface": { color: syntax.base0E, font_style: null, font_weight: null },
    "type.super": { color: syntax.base0A, font_style: null, font_weight: null },
    variable: { color: syntax.base05, font_style: null, font_weight: null },
    "variable.builtin": { color: syntax.base09, font_style: null, font_weight: null },
    "variable.member": { color: syntax.base08, font_style: null, font_weight: null },
    "variable.parameter": { color: syntax.base08, font_style: null, font_weight: null },
    "variable.special": { color: syntax.base08, font_style: "italic", font_weight: null },
    variant: { color: syntax.base0C, font_style: null, font_weight: null }
  };
};

export const buildZedThemeVariant = (theme: ThemeSpec) => {
  const base = theme.base30;
  const syntax = theme.base16;
  const mutedHint = base.lightGrey;

  return {
    name: theme.displayName,
    appearance: theme.type,
    style: {
      accents: [base.blue, base.green, base.teal, base.yellow, base.orange, base.purple, base.red],
      "background.appearance": "opaque",
      background: base.black,
      border: base.line,
      "border.disabled": base.greyFg2,
      "border.focused": base.blue,
      "border.selected": base.purple,
      "border.transparent": alpha(base.black, 0),
      "border.variant": base.oneBg3,
      conflict: base.orange,
      "conflict.background": alpha(base.orange, 0.16),
      "conflict.border": base.orange,
      created: base.green,
      "created.background": alpha(base.green, 0.16),
      "created.border": base.green,
      "debugger.accent": base.red,
      deleted: base.red,
      "deleted.background": alpha(base.red, 0.15),
      "deleted.border": base.red,
      "drop_target.background": alpha(base.blue, 0.2),
      "editor.active_line.background": lineHighlight(theme),
      "editor.active_line_number": base.blue,
      "editor.active_wrap_guide": base.lightGrey,
      "editor.background": base.black,
      "editor.debugger_active_line.background": alpha(base.orange, 0.12),
      "editor.document_highlight.bracket_background": alpha(base.purple, 0.1),
      "editor.document_highlight.read_background": alpha(base.oneBg3, 0.55),
      "editor.document_highlight.write_background": alpha(base.oneBg3, 0.55),
      "editor.foreground": base.white,
      "editor.gutter.background": base.black,
      "editor.highlighted_line.background": alpha(base.blue, 0.08),
      "editor.indent_guide": alpha(base.line, 0.8),
      "editor.indent_guide_active": base.lightGrey,
      "editor.invisible": alpha(base.grey, 0.6),
      "editor.line_number": base.greyFg,
      "editor.subheader.background": base.black2,
      "editor.wrap_guide": base.line,
      "elevated_surface.background": base.black2,
      "element.active": alpha(base.oneBg3, 0.7),
      "element.background": base.oneBg,
      "element.disabled": base.greyFg2,
      "element.hover": base.oneBg2,
      "element.selected": alpha(base.blue, 0.16),
      error: base.red,
      "error.background": alpha(base.red, 0.14),
      "error.border": base.red,
      "ghost_element.active": alpha(base.oneBg3, 0.55),
      "ghost_element.background": alpha(base.black, 0),
      "ghost_element.disabled": base.greyFg2,
      "ghost_element.hover": alpha(base.oneBg2, 0.5),
      "ghost_element.selected": alpha(base.oneBg3, 0.4),
      hidden: base.lightGrey,
      "hidden.background": base.black2,
      "hidden.border": base.lightGrey,
      hint: mutedHint,
      "hint.background": alpha(mutedHint, 0.12),
      "hint.border": alpha(mutedHint, 0.35),
      icon: base.white,
      "icon.accent": base.teal,
      "icon.disabled": base.greyFg2,
      "icon.muted": base.lightGrey,
      "icon.placeholder": base.greyFg,
      ignored: base.lightGrey,
      "ignored.background": alpha(base.lightGrey, 0.08),
      "ignored.border": base.lightGrey,
      info: base.blue,
      "info.background": alpha(base.blue, 0.14),
      "info.border": base.blue,
      "link_text.hover": base.teal,
      "minimap.thumb.active_background": alpha(base.blue, 0.45),
      "minimap.thumb.background": alpha(base.blue, 0.2),
      "minimap.thumb.border": null,
      "minimap.thumb.hover_background": alpha(base.blue, 0.3),
      modified: base.yellow,
      "modified.background": alpha(base.yellow, 0.14),
      "modified.border": base.yellow,
      "pane.focused_border": base.blue,
      "pane_group.border": base.line,
      "panel.background": base.black2,
      "panel.focused_border": base.blue,
      "panel.indent_guide": alpha(base.line, 0.8),
      "panel.indent_guide_active": base.lightGrey,
      "panel.indent_guide_hover": base.teal,
      "panel.overlay_background": base.black2,
      players: [
        { background: base.blue, cursor: base.blue, selection: alpha(base.blue, 0.3) },
        { background: base.green, cursor: base.green, selection: alpha(base.green, 0.3) },
        { background: base.teal, cursor: base.teal, selection: alpha(base.teal, 0.3) },
        { background: base.yellow, cursor: base.yellow, selection: alpha(base.yellow, 0.3) },
        { background: base.orange, cursor: base.orange, selection: alpha(base.orange, 0.3) },
        { background: base.purple, cursor: base.purple, selection: alpha(base.purple, 0.3) },
        { background: base.red, cursor: base.red, selection: alpha(base.red, 0.3) }
      ],
      predictive: base.lightGrey,
      "predictive.background": alpha(base.oneBg3, 0.2),
      "predictive.border": base.blue,
      renamed: base.teal,
      "renamed.background": alpha(base.teal, 0.14),
      "renamed.border": base.teal,
      "scrollbar.thumb.active_background": alpha(base.greyFg2, 0.82),
      "scrollbar.thumb.background": alpha(base.oneBg3, 0.65),
      "scrollbar.thumb.border": null,
      "scrollbar.thumb.hover_background": alpha(base.grey, 0.7),
      "scrollbar.track.background": base.black2,
      "scrollbar.track.border": alpha(base.black, 0),
      "search.active_match_background": alpha(base.green, 0.24),
      "search.match_background": alpha(base.teal, 0.14),
      "status_bar.background": base.statuslineBg,
      success: base.green,
      "success.background": alpha(base.green, 0.14),
      "success.border": base.green,
      "surface.background": base.black2,
      syntax: buildZedSyntax(theme),
      "tab.active_background": base.black,
      "tab.active_border_top": base.blue,
      "tab.hover_background": alpha(base.oneBg2, 0.72),
      "tab.inactive_background": base.black2,
      "tab_bar.background": base.statuslineBg,
      "terminal.ansi.background": base.black,
      "terminal.ansi.black": base.black2,
      "terminal.ansi.blue": base.blue,
      "terminal.ansi.bright_black": base.greyFg,
      "terminal.ansi.bright_blue": syntax.base0D,
      "terminal.ansi.bright_cyan": base.teal,
      "terminal.ansi.bright_green": base.vibrantGreen,
      "terminal.ansi.bright_magenta": base.darkPurple,
      "terminal.ansi.bright_red": base.babyPink,
      "terminal.ansi.bright_white": syntax.base07,
      "terminal.ansi.bright_yellow": base.sun,
      "terminal.ansi.cyan": base.cyan,
      "terminal.ansi.dim_black": base.black2,
      "terminal.ansi.dim_blue": base.nordBlue,
      "terminal.ansi.dim_cyan": base.cyan,
      "terminal.ansi.dim_green": base.green,
      "terminal.ansi.dim_magenta": base.purple,
      "terminal.ansi.dim_red": base.red,
      "terminal.ansi.dim_white": base.lightGrey,
      "terminal.ansi.dim_yellow": base.yellow,
      "terminal.ansi.green": base.green,
      "terminal.ansi.magenta": base.purple,
      "terminal.ansi.red": base.red,
      "terminal.ansi.white": base.white,
      "terminal.ansi.yellow": base.yellow,
      "terminal.background": base.black,
      "terminal.bright_foreground": syntax.base07,
      "terminal.dim_foreground": base.lightGrey,
      "terminal.foreground": base.white,
      text: base.white,
      "text.accent": base.teal,
      "text.disabled": base.greyFg2,
      "text.muted": base.lightGrey,
      "text.placeholder": base.greyFg,
      "title_bar.background": base.black2,
      "title_bar.inactive_background": base.statuslineBg,
      "toolbar.background": base.black2,
      "toolbar.hover_background": alpha(base.oneBg3, 0.9),
      unreachable: base.red,
      "unreachable.background": alpha(base.red, 0.14),
      "unreachable.border": base.red,
      "version_control.added": base.green,
      "version_control.conflict": base.orange,
      "version_control.conflict_marker.ours": alpha(base.green, 0.2),
      "version_control.conflict_marker.theirs": alpha(base.blue, 0.2),
      "version_control.deleted": base.red,
      "version_control.ignored": base.lightGrey,
      "version_control.modified": base.yellow,
      "version_control.renamed": base.teal,
      "vim.helix_normal.background": base.blue,
      "vim.helix_normal.foreground": base.black,
      "vim.helix_select.background": base.teal,
      "vim.helix_select.foreground": base.black,
      "vim.insert.background": base.green,
      "vim.insert.foreground": base.black,
      "vim.mode.text": base.white,
      "vim.normal.background": base.blue,
      "vim.normal.foreground": base.black,
      "vim.replace.background": base.red,
      "vim.replace.foreground": base.black,
      "vim.visual.background": base.purple,
      "vim.visual.foreground": base.black,
      "vim.visual_block.background": base.orange,
      "vim.visual_block.foreground": base.black,
      "vim.visual_line.background": base.yellow,
      "vim.visual_line.foreground": base.black,
      warning: base.yellow,
      "warning.background": alpha(base.yellow, 0.14),
      "warning.border": base.yellow
    }
  };
};

export const buildZedTheme = (theme: ThemeSpec): ZedThemeDefinition => ({
  $schema: "https://zed.dev/schema/themes/v0.2.0.json",
  name: theme.displayName,
  author: theme.author,
  themes: [buildZedThemeVariant(theme)]
});

export const buildZedExtensionBundle = (themes: ThemeSpec[]): ZedThemeDefinition => ({
  $schema: "https://zed.dev/schema/themes/v0.2.0.json",
  name: "NvChad Themes",
  author: "NvChad",
  themes: themes.map((theme) => buildZedThemeVariant(theme))
});
